version: "3.7"

services:
  vue:
    image: mm-vue-front
    container_name: mm-vue-front
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/jenkins/workspace:/usr/src/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8082:8082
    networks:
      - mm-network

networks:
  mm-network:
    driver: bridge